### ISSUE TITLE
关于 .github/workflow/cron.yml 的疑问

### ISSUE THREAD

**Issue by UptonEdward** [yuumimi/rules#2]
请问 .github/workflow/cron.yml 中 L70 到 L85 以及后续的类似行的作用是什么？

**Comment by yuumimi** [comment]
tiktok 在 cn@!cn 里，同时也在 cn 里，目的是删除 tiktok 等这些不应该在 cn 里的域名。
还有一个目的是让几个app的域名顺序保持一致。

更好的方法是改 .go 文件，比如在生成 cn.txt 的时候直接过滤掉 @!cn 标签的域名。

**Comment by UptonEdward** [comment]
感谢
